[https://thefiddler.substack.com/p/did-xkcd-get-its-math-right](link)
[https://xkcd.com/3015/](link)

```{r}
library(gtools)
```


determine p -> the odds you draw two non-cursed arrows from a quiver of ten, where five are cursed, and five are not cursed
```{r Arrows}

arrow_set <- 1:10 # Let 1-5 be non-cursed and 6-10 be cursed
arrow_perms <- permutations(n = 10, r = 2, v = arrow_set)
arrow_perm_count <- nrow(arrow_perms)

arrow_tester <- apply(arrow_perms[,1:2], 1, function(rww) all(rww < 6)) 
# Arrows 1-5 are non-cursed
arrow_wins <- sum(arrow_tester)

p <- arrow_wins / arrow_perm_count

sprintf("%1.4f%%", p*100)

```

- P(10,2) = 10! / (10-2)! = 10! / 8! = 10 * 9 = 90 permutations
- Also can be computed as (5/10)*(4/9)


determine q -> the odds that the sum of rolling 3x six-sided dice and one-four-sided die will add up to at least 16
```{r Dice}

roll_threshold <- 16
d6 <- 1:6
d4 <- 1:4

roll_perms <- expand.grid(d6, d6, d6, d4)
roll_perm_count <- nrow(roll_perms)
roll_row_totals <- rowSums(roll_perms) 
roll_wins <- sum(roll_row_totals >= roll_threshold)

q <- roll_wins / roll_perm_count

sprintf("%1.4f%%", q*100)

```


```{r Are They Equal?}
test <- p == q
print(test)
```

[https://thefiddler.substack.com/p/can-you-squeeze-the-particles-into](link)
